algoritmo "Missão 3- Calculo aumento do salario de 30%"
// Função :
// Autor :  Vania Ramos
// Data : 02/03/2023
// Seção de Declarações 
var

valor_salario, percentual_reajuste, novo_salario: real

Inicio
escreval ("Informe o valor salario em R$")
leia (valor_salario)

percentual_reajuste <- 1+30/100

novo_salario <- valor_salario * percentual_reajuste

escreval ("o valor do novo salario é R$", novo_salario)


fimalgoritmo
